# Copyright 2020 Adam Chalkley
#
# https://github.com/atc0005/elbow
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://help.github.com/en/github/administering-a-repository/configuration-options-for-dependency-updates

######################################################################
# Monitor Go module dependency updates
######################################################################

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Dependency"

  - package-ecosystem: "gomod"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Dependency"

  ######################################################################
  # Monitor GitHub Actions dependency updates
  ######################################################################

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "CI Dependency"

  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "CI Dependency"

  ######################################################################
  # Monitor Go updates to service as a reminder to generate new releases
  ######################################################################

  - package-ecosystem: docker
    directory: "/dependabot/docker/go"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
      - "todo/release"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Runtime"
    ignore:
      - dependency-name: "golang"
        versions:
          - ">= 1.24.0"
          - "< 1.23.0"

  - package-ecosystem: docker
    directory: "/dependabot/docker/go"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "CI"
      - "todo/release"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Go Runtime"

  ######################################################################
  # Monitor images used to build project releases
  ######################################################################

  - package-ecosystem: docker
    directory: "/dependabot/docker/builds"
    open-pull-requests-limit: 10
    target-branch: "master"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "builds"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Build Image"

  - package-ecosystem: docker
    directory: "/dependabot/docker/builds"
    open-pull-requests-limit: 10
    target-branch: "development"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "America/Chicago"
    assignees:
      - "atc0005"
    labels:
      - "dependencies"
      - "builds"
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Build Image"
