name: Go
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: golangci-lint
        run: |
          export PATH=${PATH}:$(go env GOPATH)/bin
          go get -u github.com/golangci/golangci-lint/cmd/golangci-lint
          golangci-lint run

      - name: Staticcheck
        run: |
          # add executables installed with go get to PATH
          # TODO: this will hopefully be fixed by
          # https://github.com/actions/setup-go/issues/14
          export PATH=${PATH}:$(go env GOPATH)/bin
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Build
        run: go build -v .
